name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.vars.outputs.issue-number }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run test
      - run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then \
            echo "::set-output name=issue-number::${{ github.event.number }}" \
          else \
            echo "::set-output name=issue-number::1"; fi

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - uses: actions/checkout@v2
      - if: matrix.target == 'built'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Test create comment
        uses: ./
        id: couc
        with:
          issue-number: ${{ needs.build.outputs.issue-number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown**
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

      - name: Test update comment
        uses: ./
        with:
          comment-id: ${{ steps.couc.outputs.comment-id }}
          body: |
            **Edit:** Some additional info
          reactions: eyes

      - name: Test add reactions
        uses: ./
        with:
          comment-id: ${{ steps.couc.outputs.comment-id }}
          reactions: heart, hooray, laugh

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update distribution
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update distribution
          body: |
            - Updates the distribution for changes on `master`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution
