name: Update Comment
on:
  issue_comment:
    types: [created]
jobs:
  updateComment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # For debugging purposes. Remove this in production.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Update comment
        if: github.event.issue.number == 1
        uses: ./
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            **Edit:** Some additional info
          reaction-type: eyes

      - name: Add reaction
        if: github.event.issue.number == 1
        uses: ./
        with:
          comment-id: ${{ github.event.comment.id }}
          reaction-type: heart
